name: Update blocklist

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'
   
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - uses: fregante/setup-git-user@v2
    - name: Fetch
      run: | 
        curl -O https://raw.githubusercontent.com/LittleJake/ip-blacklist/main/ustc_blacklist_ip.txt
        curl -O https://raw.githubusercontent.com/LittleJake/ip-blacklist/main/abuseipdb_blacklist_ip_score_75.txt
        curl -O https://raw.githubusercontent.com/stamparm/ipsum/master/levels/3.txt
        curl -O https://raw.githubusercontent.com/romainmarcoux/malicious-ip/main/full-aa.txt
        for F in `ls *.txt`;do echo "">> $F; done
        cat *.txt|grep -v "#"|grep -v ":"|grep -v '^$'|sort|uniq > bad-ips.txt
    - name: Commit
      run: |
        git add bad-ips.txt
        git commit -m "Update IPs (Total `wc -l bad-ips.txt | cut -d ' ' -f 1,1` IPs)" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 
